version: "2"
services:
#   postgresql:
#     image: postgis/postgis:latest
# #    restart: n
#     environment:
#       - POSTGRES_DB=pitbull
#       - POSTGRES_USER=pitbull
#       - POSTGRES_PASSWORD=pitbull
#       #- POSTGRES_HOST_AUTH_METHOD=trust
#     ports:
#       - 5432:5432
#     expose:
#       - 5432
#     volumes:
#       - ./data:/var/lib/postgresql/data
#       - ./postgresql/:/docker-entrypoint-initdb.d/
#     mem_limit: 1024m
#     container_name: "pitbull_postgres"

  pitbull_extract:
    build: ./python-image
#    restart: always
    ports:
      - "32679:32679"
    volumes:
      - ../:/pitbull
    mem_limit: 1024m
    environment:
      - PYTHONPATH=/pitbull
    entrypoint: /usr/local/bin/python3 /pitbull/data/extract/ark/ark_download.py
    container_name: "app_get_data"
    # depends_on: 
    #   - postgresql
